removed styles
commsq/commsq-frontend pull request #16
Opened 2021-04-06 03:00 UTC by mallockey

2021-04-06 10:22 UTC, Penspinner requested changes

2021-04-06 10:22 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +  function clearLastSuggestion(): void {
No need to type function return values unless needed. Leverage TypeScript's type inference.

```suggestion
  function clearLastSuggestion() {
```

2021-04-06 10:22 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +  function handleHover(event: React.ChangeEvent<HTMLInputElement>): void {
```suggestion
  function handleHover(event: React.ChangeEvent<HTMLInputElement>) {
```

2021-04-06 10:22 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +  function handleKeyDown(event: KeyboardEvent): void {
```suggestion
  function handleKeyDown(event: KeyboardEvent) {
```

2021-04-06 10:22 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +  function handleInput(event: React.ChangeEvent<HTMLInputElement>): void {
```suggestion
  function handleInput(event: React.ChangeEvent<HTMLInputElement>) {
```

2021-04-06 10:22 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +  async function submitBuilding({ description }: SubmitBuildingProps): Promise<void> {
```suggestion
  async function submitBuilding({ description }: SubmitBuildingProps) {
```

2021-04-06 10:25 UTC, Penspinner commented
You should not be using `document` methods to query for the buttons. A representation of the database values should be stored in state, and you should be looping through that state to render the buttons. You could use `react-query` to have that abstracted out for you. This could be done in a separate PR though.

2021-04-06 21:02 UTC, mallockey commented
> You should not be using `document` methods to query for the buttons. A representation of the database values should be stored in state, and you should be looping through that state to render the buttons. You could use `react-query` to have that abstracted out for you. This could be done in a separate PR though.

But the data is not from the database it's from googles places autocomplete API. Does this still apply?

2021-04-27 01:47 UTC, Penspinner requested changes
Don't remove `package-lock.json`. We need that for npm.

2021-04-27 01:47 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +    listElements ? (listElements[highLightedIndex].className = '') : ''
```suggestion
    listElements?.[highLightedIndex].className = ''
```

2021-04-27 01:47 UTC, Penspinner commented on src/components/PlacesAutocomplete.tsx
> +    }
```suggestion
    listElements?.forEach((item, currentIndex) => {
      if (selectedIndex !== currentIndex) {
        item.className = ''
      }
    })
```

2021-05-25 03:09 UTC, merged